<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mETA" nsURI="http://www.example.org/mETA" nsPrefix="mETA">
  <eClassifiers xsi:type="ecore:EClass" name="SystemSDL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalsystem" lowerBound="1"
        upperBound="-1" eType="#//CanalSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" upperBound="-1"
        eType="#//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        upperBound="-1" eType="#//Signal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
        upperBound="-1" eType="#//Process" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connect" lowerBound="1"
        upperBound="-1" eType="#//Connect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
        upperBound="-1" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalblock" lowerBound="1"
        upperBound="-1" eType="#//CanalBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CanalSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalsystem" eType="#//CanalSystem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CanalBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalblock" eType="#//CanalBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalsystem" eType="#//CanalSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="canalblock" eType="#//CanalBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
</ecore:EPackage>
